//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoC_EF_TPT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationImport : Operation
    {
        public Nullable<System.Guid> OperationExportId { get; set; }
        public string ImportBasePath { get; set; }
    
        public virtual OperationExport OperationExport { get; set; }
    }
}
